version: "3.3"

services:
  resolve-dependencies:
    image: robsokolowski/ds-kit:latest
    volumes:
      - ./:/home/appuser/workspace
    working_dir: /home/appuser/workspace
    networks:
      - ds-kit-network
    command: pip-compile -r ./requirements.in --resolver=backtracking

  jupyter:
    image: robsokolowski/ds-kit:latest
    volumes:
      - ./:/home/appuser/workspace
      - $HOME/data:/home/appuser/data
    working_dir: /home/appuser/workspace
    ports:
      - "8888:8888"
    networks:
      - ds-kit-network
    command: jupyter lab --ip 0.0.0.0

networks:
  ds-kit-network:
    driver: bridge
    ipam:
      driver: default
